### ISSUE TITLE
在辛达强权酒吧进入某随机事件后点继续100%闪退

### ISSUE THREAD

**Issue by Catteenblu** [TruthOriginem/Starsector-096-Localization#18]
报错窗口和最后闪退时画面截图
![报错窗口](https://github.com/TruthOriginem/Starsector-096-Localization/assets/146823832/a1a86c54-502b-40ea-845b-2bb93b6e2a27)

 #![游戏截图](https://github.com/TruthOriginem/Starsector-096-Localization/assets/146823832/efca6995-8ef5-4524-a5bd-6cd012ce24b1)

游戏版本：		0.96a-RC10

### 系统信息

操作系统：Microsoft Windows 10 专业版

版本：10.0.19045 暂缺 Build 19045

总可用内存：`15.97G`

Java版本：`1.7.0_79`

Java路径：H:\BaidiYundownload\Starsector\jre

[游戏日志]

185506 [Thread-7] INFO  sound.oo0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  - Cleaning up music with id [faction_diktat_market_01_neutral.ogg]
185649 [Thread-9] INFO  sound.oo0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  - Creating streaming player for music with id [faction_diktat_market_01_neutral.ogg]
185650 [Thread-9] INFO  sound.H  - Playing music with id [faction_diktat_market_01_neutral.ogg]
185684 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.util.MissingFormatArgumentException: Format specifier 's'
java.util.MissingFormatArgumentException: Format specifier 's'
	at java.util.Formatter.format(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.lang.String.format(Unknown Source)
	at com.fs.starfarer.ui.newui.D.addPara(Unknown Source)
	at com.fs.starfarer.ui.newui.D.addPara(Unknown Source)
	at com.fs.starfarer.ui.newui.D.addPara(Unknown Source)
	at com.fs.starfarer.api.impl.campaign.intel.bar.events.BaseGetCommodityBarEvent.optionSelected(BaseGetCommodityBarEvent.java:315)
	at com.fs.starfarer.api.impl.campaign.intel.bar.BarEventDialogPlugin.optionSelected(BarEventDialogPlugin.java:53)
	at com.fs.starfarer.ui.newui.classsuper$1.o00000(Unknown Source)
	at com.fs.starfarer.ui.newui.OoOO.actionPerformed(Unknown Source)
	at com.fs.starfarer.ui.n.buttonPressed(Unknown Source)
	at com.fs.starfarer.ui.I.?00000(Unknown Source)
	at com.fs.starfarer.ui.I.processInput(Unknown Source)
	at com.fs.starfarer.ui.W.super(Unknown Source)
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)

虚拟机参数：java.exe -XX:CompilerThreadPriority=1 -XX:+CompilerThreadHintNoPreempt -Djava.library.path=native\\windows -Xms4096m -Xmx4096m -Xss2048k -XX:MaxPermSize=128m -classpath janino.jar;commons-compiler.jar;commons-compiler-jdk.jar;starfarer.api.jar;starfarer_obf.jar;jogg-0.0.7.jar;jorbis-0.0.15.jar;json.jar;lwjgl.jar;jinput.jar;log4j-1.2.9.jar;lwjgl_util.jar;fs.sound_obf.jar;fs.common_obf.jar;xstream-1.4.10.jar -Dcom.fs.starfarer.settings.paths.saves=..\\saves -Dcom.fs.starfarer.settings.paths.screenshots=..\\screenshots -Dcom.fs.starfarer.settings.paths.mods=..\\mods -Dcom.fs.starfarer.settings.paths.logs=. com.fs.starfarer.StarfarerLauncher

堆栈初始大小(`-Xms`)：`4096m`

堆栈最大大小(`-Xmx`)：`4096m`

### Mod信息

|Mod名称                           |Mod版本   |已启用     |
|-|-|-|
|[N]碧蓝档案头像包v1.06 0.96a-RC8       |1.06    |是       |

（以上内容由 远行星号 报错信息收集工具 自动生成，生成工具版本 `1.1.2`）.
[/md]

**Comment by TruthOriginem** [comment]
已尝试修复，需要后继反馈

**Comment by Catteenblu** [comment]
@TruthOriginem 
下载并覆盖了最新汉化，但闪退bug仍旧。
[游戏日志]

60530 [Thread-9] INFO  sound.H  - Playing music with id [faction_diktat_market_01_neutral.ogg]
62611 [Thread-3] INFO  sound.oo0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  - Cleaning up music with id [miscallenous_corvus_campaign_music.ogg]
62615 [Thread-7] INFO  sound.oo0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  - Cleaning up music with id [faction_diktat_market_01_neutral.ogg]
62773 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.util.MissingFormatArgumentException: Format specifier 's'
java.util.MissingFormatArgumentException: Format specifier 's'
	at java.util.Formatter.format(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.lang.String.format(Unknown Source)
	at com.fs.starfarer.ui.newui.D.addPara(Unknown Source)
	at com.fs.starfarer.ui.newui.D.addPara(Unknown Source)
	at com.fs.starfarer.ui.newui.D.addPara(Unknown Source)
	at com.fs.starfarer.api.impl.campaign.intel.bar.events.BaseGetCommodityBarEvent.optionSelected(BaseGetCommodityBarEvent.java:315)
	at com.fs.starfarer.api.impl.campaign.intel.bar.BarEventDialogPlugin.optionSelected(BarEventDialogPlugin.java:53)
	at com.fs.starfarer.ui.newui.classsuper$1.o00000(Unknown Source)
	at com.fs.starfarer.ui.newui.OoOO.actionPerformed(Unknown Source)
	at com.fs.starfarer.ui.n.buttonPressed(Unknown Source)
	at com.fs.starfarer.ui.I.?00000(Unknown Source)
	at com.fs.starfarer.ui.I.processInput(Unknown Source)
	at com.fs.starfarer.ui.W.super(Unknown Source)
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
63034 [Thread-9] INFO  sound.oo0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  - Creating streaming player for music with id [faction_diktat_market_01_neutral.ogg]

**Comment by TruthOriginem** [comment]
忘记这里是内核问题了，还是需要后继修复

**Comment by Catteenblu** [comment]
安装覆盖10.8最新汉化后，读档尝试触发该事件，可成功触发且正常交互
![已解决](https://github.com/TruthOriginem/Starsector-096-Localization/assets/146823832/5c54c170-aa78-44af-8f4f-93c6a0765fe1)
