### ISSUE TITLE
10月2日更新导致无法执行突袭行动

### ISSUE THREAD

**Issue by templarfenix** [TruthOriginem/Starsector-096-Localization#19]
在殖民地点击 1.获取贵重物品... 或者 2.瘫痪特定... 后返回红字NullPointerException：Null

**Comment by jnxyp** [comment]
```
513417 [Thread-3] WARN  com.fs.starfarer.campaign.rules.oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  - Problem with command of class com.fs.starfarer.api.impl.campaign.rulecmd.salvage.MarketCMD: null
java.lang.NullPointerException
```


```
47754 [Thread-3] WARN  com.fs.starfarer.campaign.rules.oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO  - Problem with command of class com.fs.starfarer.api.impl.campaign.rulecmd.salvage.MarketCMD: null
java.lang.NullPointerException
	at com.fs.starfarer.campaign.ui.marketinfo.C.setNumIcons(Unknown Source)
	at com.fs.starfarer.campaign.ui.marketinfo.ooO0.autoSizeTo(Unknown Source)
	at com.fs.starfarer.campaign.ui.marketinfo.ooO0.autoSizeWithAdjust(Unknown Source)
	at com.fs.starfarer.campaign.ui.marketinfo.GroundRaidTargetPickerDialog.createUI(Unknown Source)
	at com.fs.starfarer.campaign.ui.marketinfo.GroundRaidTargetPickerDialog.<init>(Unknown Source)
	at com.fs.starfarer.ui.newui.classsuper.showGroundRaidTargetPicker(Unknown Source)
	at com.fs.starfarer.api.impl.campaign.rulecmd.salvage.MarketCMD.raidValuable(MarketCMD.java:1069)
	at com.fs.starfarer.api.impl.campaign.rulecmd.salvage.MarketCMD.execute(MarketCMD.java:344)
	at com.fs.starfarer.campaign.rules.oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.execute(Unknown Source)
	at com.fs.starfarer.campaign.rules.C.runScript(Unknown Source)
	at com.fs.starfarer.api.impl.campaign.rulecmd.FireBest.applyRule(FireBest.java:106)
	at com.fs.starfarer.api.impl.campaign.rulecmd.FireBest.execute(FireBest.java:51)
	at com.fs.starfarer.api.impl.campaign.rulecmd.FireBest.fire(FireBest.java:57)
	at com.fs.starfarer.api.impl.campaign.RuleBasedInteractionDialogPluginImpl.fireBest(RuleBasedInteractionDialogPluginImpl.java:177)
	at com.fs.starfarer.api.impl.campaign.RuleBasedInteractionDialogPluginImpl.optionSelected(RuleBasedInteractionDialogPluginImpl.java:210)
	at com.fs.starfarer.ui.newui.classsuper$1.o00000(Unknown Source)
	at com.fs.starfarer.ui.newui.OoOO.actionPerformed(Unknown Source)
	at com.fs.starfarer.ui.n.buttonPressed(Unknown Source)
	at com.fs.starfarer.ui.I.?00000(Unknown Source)
	at com.fs.starfarer.ui.I.processInput(Unknown Source)
	at com.fs.starfarer.ui.n.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.processInput(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.dispatchEventsToChildren(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.newui.OoOO.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.processInput(Unknown Source)
	at com.fs.starfarer.ui.g$Oo.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.processInput(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.dispatchEventsToChildren(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.g.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.processInput(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.dispatchEventsToChildren(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.public.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.newui.classsuper.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.processInput(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.dispatchEventsToChildren(Unknown Source)
	at com.fs.starfarer.ui.interfacenew.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.thissuper.processInput(Unknown Source)
	at com.fs.starfarer.campaign.CampaignState.processInput(Unknown Source)
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by 1847905557** [comment]
解决

**Comment by 827053088zxc** [comment]
怎么解决呀
